# docker-compose เอาไว้แยก services แยก container ของ node กับ mongo ออกมา แล้ว map หากัน
# สร้าง image และเชื่อมต่อกันระหว่าง contaioner node กับ mongo
# คล้ายๆ คำสั่ง bind mount เพื่อเอา folder host sync กับ folder ใน container docker run -d -p 80:3000 -v $(pwd):/site dockeruser/container_name:tag

version: "3"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
      # build คือ build image base on Dockerfile จากไหน (. คือ current dir)
      # link ไปเรียก mongo container
      # pull image from docker hub
